<a href="https://colab.research.google.com/github/3b232078/2026_DL_hws/blob/main/hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 深度學習 作業 1

## 一、模擬多隱藏層的全連接神經網路(DNN)

### 1.載入numpy套件

In [67]:
import numpy as np

### 2.定義激發函數

In [68]:
def relu(x):
    return np.maximum(0, x)

In [69]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [70]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x))

### 3.輸入層資料(6個特徵值)

In [71]:
X = np.array([0.5, -1.2, 3.3, 0.8, -0.7, 2.1])
print(X)
print(X.shape)

[ 0.5 -1.2  3.3  0.8 -0.7  2.1]
(6,)


### 4.第一隱藏層

In [72]:
# 5個神經元

W1 = np.array([
    [0.1, 0.2, 0.3, 0.4, 0.5],
    [0.5, 0.4, 0.3, 0.2, 0.1],
    [0.2, 0.3, 0.4, 0.5, 0.6],
    [0.6, 0.5, 0.4, 0.3, 0.2],
    [0.3, 0.4, 0.5, 0.6, 0.7],
    [0.7, 0.6, 0.5, 0.4, 0.3]])

b1 = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
print(W1.shape)
print(b1.shape)

(6, 5)
(5,)


In [73]:
# 加權和

z1 = np.dot(X, W1) + b1
print(z1)
print(z1.shape)

[1.95 2.19 2.43 2.67 2.91]
(5,)


In [74]:
# 激活函數 ReLU

h1 = relu(z1)
print(h1)
print(h1.shape)

[1.95 2.19 2.43 2.67 2.91]
(5,)


### 5.第二隱藏層

In [75]:
# 4個神經元

W2 = np.array([
    [0.2, 0.3, 0.4, 0.5],
    [0.5, 0.4, 0.3, 0.2],
    [0.3, 0.4, 0.5, 0.6],
    [0.6, 0.5, 0.4, 0.3],
    [0.4, 0.5, 0.6, 0.7],])

b2 = np.array([0.2, 0.3, 0.4, 0.5])
print(W2.shape)
print(b2.shape)

(5, 4)
(4,)


In [76]:
# 加權和

z2 = np.dot(h1, W2) + b2
print(z2)
print(z2.shape)

[5.18  5.523 5.866 6.209]
(4,)


In [77]:
# 激活函數 ReLU

h2 = relu(z2)
print(h2)
print(h2.shape)

[5.18  5.523 5.866 6.209]
(4,)


### 6.第三隱藏層

In [78]:
# 4個神經元

W3 = np.array([
    [0.3, 0.4, 0.5, 0.6],
    [0.4, 0.5, 0.6, 0.7],
    [0.5, 0.6, 0.7, 0.8],
    [0.6, 0.7, 0.8, 0.9]])

b3 = np.array([0.1, 0.2, 0.3, 0.4])
print(W3.shape)
print(b3.shape)

(4, 4)
(4,)


In [79]:
# 加權和

z3 = np.dot(h2, W3) + b3
print(z3)
print(z3.shape)

[10.5216 12.8994 15.2772 17.655 ]
(4,)


In [80]:
# 激活函數 sigmoid

h3 = sigmoid(z3)
print(h3)
print(h3.shape)

[0.99997305 0.9999975  0.99999977 0.99999998]
(4,)


### 7.輸出層

In [81]:
# 3個神經元
W4 = np.array([
    [0.5, 0.3, 0.1],
    [0.2, 0.4, 0.6],
    [0.7, 0.5, 0.3],
    [0.6, 0.2, 0.4]])

b4 = np.array([0.4, 0.5, 0.6])
print(W4.shape)
print(b4.shape)

(4, 3)
(3,)


In [82]:
# 加權和

z4 = np.dot(h3, W4) + b4
print(z4)
print(z4.shape)

[2.39998585 1.8999908  1.99999573]
(3,)


In [83]:
# 激活函數 Softmax

y_hat = softmax(z4)
print(y_hat)
print(y_hat.shape)

[0.43920129 0.26639037 0.29440834]
(3,)


### 8.使用cross_entropy_erro計算誤差值

In [84]:
# 計算神經網路計算出的結果y_hat與真正的結果y之間的誤差
def cross_entropy_error(y_hat, y):
    return -np.sum(y * np.log(y_hat + 1e-7))

In [85]:
# 假設第三種為真實結果
y=[0, 0, 1]

In [86]:
np.log(y_hat + 1e-7)

array([-0.82279722, -1.32279212, -1.22278723])

In [87]:
y*np.log(y_hat + 1e-7)

array([-0.        , -0.        , -1.22278723])

In [88]:
-np.sum(y * np.log(y_hat + 1e-7))

np.float64(1.2227872276998428)

In [89]:
cross_entropy_error(y_hat, y)

np.float64(1.2227872276998428)

## 二、設計dnn函數，搭配Gradio套件

In [90]:
import gradio as gr

def dnn(x):
  # 第一隱藏層
  W1 = np.array([
    [0.1, 0.2, 0.3, 0.4, 0.5],
    [0.5, 0.4, 0.3, 0.2, 0.1],
    [0.2, 0.3, 0.4, 0.5, 0.6],
    [0.6, 0.5, 0.4, 0.3, 0.2],
    [0.3, 0.4, 0.5, 0.6, 0.7],
    [0.7, 0.6, 0.5, 0.4, 0.3]])

  b1 = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
  z1 = np.dot(x, W1) + b1
  h1 = relu(z1)

  # 第二隱藏層
  W2 = np.array([
    [0.2, 0.3, 0.4, 0.5],
    [0.5, 0.4, 0.3, 0.2],
    [0.3, 0.4, 0.5, 0.6],
    [0.6, 0.5, 0.4, 0.3],
    [0.4, 0.5, 0.6, 0.7],])

  b2 = np.array([0.2, 0.3, 0.4, 0.5])
  z2 = np.dot(h1, W2) + b2
  h2 = relu(z2)

  # 第三隱藏層
  W3 = np.array([
    [0.3, 0.4, 0.5, 0.6],
    [0.4, 0.5, 0.6, 0.7],
    [0.5, 0.6, 0.7, 0.8],
    [0.6, 0.7, 0.8, 0.9]])

  b3 = np.array([0.1, 0.2, 0.3, 0.4])
  z3 = np.dot(h2, W3) + b3
  h3 = sigmoid(z3)

  # 輸出層
  W4 = np.array([
    [0.5, 0.3, 0.1],
    [0.2, 0.4, 0.6],
    [0.7, 0.5, 0.3],
    [0.6, 0.2, 0.4]])

  b4 = np.array([0.4, 0.5, 0.6])
  z4 = np.dot(h3, W4) + b4
  y_hat = softmax(z4)
  # y_hat為最終計算的各項機率結果
  return y_hat

### 建立 Gradio 介面

In [91]:
def classify_input(x1, x2, x3, x4, x5, x6):
  x = np.array([x1, x2, x3, x4, x5, x6]).reshape(1, 6)
  y_hat = dnn(x)

  return np.argmax(y_hat) + 1

interface = gr.Interface(fn=classify_input,inputs=[gr.Number(label=f"Feature {i}") for i in range(1, 7)], outputs="text", title="DNN Classifier", description="輸入6個特徵值，模型將輸出機率最高的類別 (1, 2, 3)")

# 啟動介面
interface.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://fe04949556de6ad0b2.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
